version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    security-updates:
      enabled: true
    groups:
      security:
        patterns:
          - 'react*'
          - 'next'
        update-types:
          - 'patch'
          - 'minor'
