version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    groups:
      security:
        patterns:
          - 'react*'
          - 'next'
        update-types:
          - 'patch'
          - 'minor'
      allow:
        - dependency-type: 'direct'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
