'use client';

import { useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { useMutation, useQuery } from 'urql';

// These will be generated by GraphQL Code Generator
const LoginDocument = `
  mutation Login($email: String!, $password: String!) {
    login(email: $email, password: $password) {
      accessToken
      refreshToken
      user {
        id
        email
        firstName
        lastName
        role
      }
    }
  }
`;

const RegisterDocument = `
  mutation Register($email: String!, $password: String!, $firstName: String!, $lastName: String!) {
    register(email: $email, password: $password, firstName: $firstName, lastName: $lastName) {
      accessToken
      refreshToken
      user {
        id
        email
        firstName
        lastName
      }
    }
  }
`;

const MeDocument = `
  query Me {
    me {
      id
      email
      firstName
      lastName
      phone
      role
      avatar
      discountRate
      isVerified
    }
  }
`;

export function useAuth() {
  const router = useRouter();

  const [loginResult, loginMutation] = useMutation(LoginDocument);
  const [registerResult, registerMutation] = useMutation(RegisterDocument);
  const [meResult, refetchMe] = useQuery({ query: MeDocument });

  const login = useCallback(
    async (email: string, password: string) => {
      const result = await loginMutation({ email, password });

      if (result.data?.login) {
        const { accessToken, refreshToken } = result.data.login;
        localStorage.setItem('accessToken', accessToken);
        localStorage.setItem('refreshToken', refreshToken);
        await refetchMe({ requestPolicy: 'network-only' });
        return result.data.login;
      }

      throw new Error(result.error?.message || 'Login failed');
    },
    [loginMutation, refetchMe],
  );

  const register = useCallback(
    async (email: string, password: string, firstName: string, lastName: string) => {
      const result = await registerMutation({ email, password, firstName, lastName });

      if (result.data?.register) {
        const { accessToken, refreshToken } = result.data.register;
        localStorage.setItem('accessToken', accessToken);
        localStorage.setItem('refreshToken', refreshToken);
        await refetchMe({ requestPolicy: 'network-only' });
        return result.data.register;
      }

      throw new Error(result.error?.message || 'Registration failed');
    },
    [registerMutation, refetchMe],
  );

  const logout = useCallback(() => {
    localStorage.removeItem('accessToken');
    localStorage.removeItem('refreshToken');
    router.push('/login');
  }, [router]);

  return {
    user: meResult.data?.me,
    isLoading: meResult.fetching || loginResult.fetching || registerResult.fetching,
    isAuthenticated: !!meResult.data?.me,
    login,
    register,
    logout,
    refetchUser: refetchMe,
  };
}
